#region Legal
/*
Copyright (c) 2015-2025, AccurateAppend Corp
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#endregion

namespace Net_8_Sample_code.Models.Request
{
    /// <summary>
    /// 
    /// </summary>
    class JobSubmit
    {
        /// <summary>
        /// A value generated by you to uniquely identify your file. 
        /// The value must be a Universally unique identifier (we suggest using the v4 format for your generation of identifiers).
        /// </summary>
        public Guid RequestId { get; set; }

        /// <summary>
        /// Your API Key, found in your account profile.
        /// </summary>
        public Guid ApiKey { get; set; }

        /// <summary>
        /// The name of your pre-configured product. 
        /// These are the same as available on the client portal when uploading files via our website. 
        /// If you need to have new products created or update existing ones please contact support.
        /// </summary>
        public String ProductName { get; set; }

        /// <summary>
        /// A ';' delimited list of Field Names matching your file content columns. 
        /// This is used to identify what data is in each column and if it should be used or ignored for appending. 
        /// If this is not supplied we will attempt to identify what data is present in your file 
        /// but cannot guarantee this will always work for your file.
        /// </summary>
        public String ColumnMap { get; set; }

        /// <summary>
        /// The path of the .csv file that would be converted and send to the endpoint.
        /// </summary>
        public String FilePath { get; set; }

        /// <summary>
        /// Used to identify how columns are identified. 
        /// We support ',' (comma), '|' (pipe), and the \t (tab) character. 
        /// If omitted, we will assume the ',' character is used.
        /// </summary>
        public Char Delimiter { get; set; } = ',';

    }
}
